---
abstract: 'Cookie Based Access and Authorization Module'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Apache::Test: 0
  Apache::TestRequest: 0
  Apache::TestRunPerl: 0
  DBD::SQLite: 0
  Exporter: 0
  Fatal: 0
  File::Basename: 0
  File::Path: 0
  File::Spec::Functions: 0
  Module::Signature: 0
  Socket: 0
  Test::More: 0
  mod_perl: 0
  mod_perl2: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-AuthTicket
requires:
  Apache2::AuthCookie: 0
  Apache2::Connection: 0
  Apache2::Const: 0
  Apache2::RequestIO: 0
  Apache2::ServerUtil: 0
  Apache::AuthCookie: 0
  Apache::Constants: 0
  Apache::Log: 0
  Apache::Test: 1.35
  CGI: 3.12
  Class::Accessor::Fast: 0
  DBI: 0
  Digest::MD5: 0
  MRO::Compat: 0
  ModPerl::VersionUtil: 0
  SQL::Abstract: 0
  constant: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Apache-AuthTicket
  homepage: http://search.cpan.org/dist/Apache-AuthTicket/
  repository: git://github.com/mschout/apache-authticket.git
version: 0.91
